title: TIMELIB
description: A lightweight C++ library designed for time measurement and benchmarking.
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
