title: CMDLP
description: A c++ command-line parsing library
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
